INSERT INTO TB_USER (USER_ID, USER_NAME, PASSWORD, ENABLED) VALUES ('joyoungc', 'joyoungc', '1234', 1);
INSERT INTO TB_USER (USER_ID, USER_NAME, PASSWORD, ENABLED) VALUES ('aiden', 'aiden', 'qwer', 1);

INSERT INTO TB_USER_AUTH (USER_ID, AUTHORITY) VALUES ('joyoungc', 'ROLE_USER');
INSERT INTO TB_USER_AUTH (USER_ID, AUTHORITY) VALUES ('joyoungc', 'ROLE_ADMIN');
INSERT INTO TB_USER_AUTH (USER_ID, AUTHORITY) VALUES ('aiden', 'ROLE_USER');