INSERT INTO TB_ADM_LOGIN VALUES ('joyoungc', '1234', true);
INSERT INTO TB_ADM_LOGIN VALUES ('aiden', 'qwer', true);
INSERT INTO TB_ADM_LOGIN VALUES ('jeong', 'asdf', true);

INSERT INTO TB_ADM_AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('joyoungc', 'ROLE_USER');
INSERT INTO TB_ADM_AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('joyoungc', 'ROLE_ADMIN');
INSERT INTO TB_ADM_AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('aiden', 'ROLE_USER');
INSERT INTO TB_ADM_AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('jeong', 'ROLE_ETC');