INSERT INTO TB_USER (USR_ID, USR_NM, PASSWORD, ENABLED) VALUES ('joyoungc', 'joyoungc', '1234', 1);
INSERT INTO TB_USER (USR_ID, USR_NM, PASSWORD, ENABLED) VALUES ('aiden', 'aiden', 'qwer', 1);

INSERT INTO TB_USER_AUTH (USR_ID, ATH_CD) VALUES ('joyoungc', 'ROLE_USER');
INSERT INTO TB_USER_AUTH (USR_ID, ATH_CD) VALUES ('joyoungc', 'ROLE_ADMIN');
INSERT INTO TB_USER_AUTH (USR_ID, ATH_CD) VALUES ('aiden', 'ROLE_USER');